spring.application.name=backend

# MySQL
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# MongoDB Atlas
spring.mongodb.uri=mongodb+srv://nishaarumugam73_db_user:Repairability@repairiqcluster.vdgh54l.mongodb.net/?appName=RepairIQCluster
spring.mongodb.database=repairiq_ai

# Email / OTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nishaarumugam73@gmail.com
spring.mail.password=gpafuhocmgbmcats 
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# Railway database configuration